#!/bin/sh

if [ -x /Applications/XLStream.app/XLStreamLauncher ]; then
    PREFIX=""
else
    PREFIX="/var/jb"
fi
PLIST="${PREFIX}/Library/LaunchDaemons/com.jibeib.xlstreamd.plist"
(
    launchctl bootout system/com.jibeib.xlstreamd || true
    launchctl unload "$PLIST" || true
    killall XLStreamLauncher || true
    killall xlstreamd || true
) </dev/null >/dev/null 2>&1 &
exit 0
